---

# Any ignore directives should be uncommented in downstream projects to disable
# Dependabot updates for the given dependency. Downstream projects will get
# these updates when the pull request(s) in the appropriate skeleton are merged
# and Lineage processes these changes.

updates:
  - directory: /
    ignore:
      # Managed by cisagov/skeleton-generic
      - dependency-name: actions/cache
      - dependency-name: actions/checkout
      - dependency-name: actions/setup-go
      - dependency-name: actions/setup-python
      - dependency-name: crazy-max/ghaction-dump-context
      - dependency-name: crazy-max/ghaction-github-labeler
      - dependency-name: crazy-max/ghaction-github-status
      - dependency-name: hashicorp/setup-terraform
      - dependency-name: mxschmitt/action-tmate
      - dependency-name: step-security/harden-runner
      # Managed by cisagov/skeleton-python-library
      - dependency-name: actions/download-artifact
      - dependency-name: actions/upload-artifact
      - dependency-name: github/codeql-action/analyze
      - dependency-name: github/codeql-action/autobuild
      - dependency-name: github/codeql-action/init
    package-ecosystem: github-actions
    schedule:
      interval: weekly

  - directory: /
    package-ecosystem: pip
    schedule:
      interval: weekly

  - directory: /
    package-ecosystem: terraform
    schedule:
      interval: weekly
version: 2
